### ISSUE TITLE
add default flag to sass variables

### ISSUE THREAD

**Issue by joernroeder** [andriussev/timelined#2]
I'm currently trying to override some sass variables which seems impossible if you're not touching the module (i've added timelined via npm) files. Consider the following use case:

```scss
@import 'timeline_settings'; // overrides some sass variables
@import 'timeline'; // variables reassign themself
```

Adding the `!default` flag to the variables prevents reassignment:

> You can assign to variables if they aren’t already assigned by adding the `!default` flag to the end of the value. This means that if the variable has already been assigned to, it won’t be re-assigned, but if it doesn’t have a value yet, it will be given one.

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_

**Comment by andriussev** [comment]
Thank you for the pull request. I haven't been really using this project much these days.

**Comment by joernroeder** [comment]
you're welcome. thx for the quick merge :)
